# Generated by Django 5.1.5 on 2025-04-17 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0002_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="uesr",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
