# Generated by Django 5.1.5 on 2025-04-17 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0003_task_uesr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="uesr",
            new_name="user",
        ),
    ]
