# Generated by Django 5.1.5 on 2025-04-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0004_rename_uesr_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
